# Generated by Django 3.2.19 on 2025-03-18 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albums',
            old_name='description',
            new_name='descripcion',
        ),
    ]
